abstract: Configurator implementation with YAML
author: 'Florian Merges <fmerges@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Log-Dispatch-Configurator-YAML
no_index:
  directory:
    - inc
    - t
requires:
  Log::Dispatch::Config: 0
version: 0.01
