--- 
abstract: Configurator implementation with YAML
author: Florian Merges <fmerges@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Log-Dispatch-Configurator-YAML
no_index: 
  directory: 
    - inc
    - t
requires: 
  Log::Dispatch::Config: 0
  YAML: 0
version: 0.03
